name: notebooksenv
channels:
- conda-forge
dependencies:
- python==3.7.3
- pip==19.*
- pip:
  - cython==0.29.8
  - numpy==1.16.4
  - scipy==1.3.1
  - matplotlib=3.0.3
  - qutip==4.5.1
- imagemagick=7.0.8_49
